[package]
name = "oqs-sys"
version = "0.2.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
edition = "2018"
links = "oqs"
description = "Bindings to liboqs"
readme = "../README.md"
repository = "https://github.com/open-quantum-safe/liboqs-rust"
license = "MIT or Apache-2.0"

# Exclude certain liboqs files
exclude = ["liboqs/tests/**", "liboqs/scripts/**", "build/**/*.o"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake = "0.1"
bindgen = "0.55"
build-deps = "0.1"

[features]
default = ["openssl"]
openssl = []
docs = []

[package.metadata.docs.rs]
features = ["docs"]
